feat: allow good peers to be saved and dial on reloads
waku-org/examples.waku.org pull request #262
Opened 2023-08-07 11:38 UTC by danisharora099

!! not to be merged !!

Reference for https://github.com/waku-org/js-waku/issues/1463

This PR allows this example to save "good" peers -- peers who we have successfully been able to dial previously, in the local storage, and allows for easy redials the next time we start the example (ensuring that the local storage isn't wiped)

2023-08-07 13:13 UTC, weboko commented on examples/web-chat/src/Room.tsx
> +    (async () => {
let's reject the promise on unmount

2023-08-07 13:16 UTC, weboko commented on examples/web-chat/src/utils.ts
> +export async function saveMultiaddrsToLocalStorage(
I think it should be integrated into `js-waku`s core code. 

@waku-org/js-waku-developers wdyt?

2023-08-08 04:05 UTC, fryorcraken requested changes
This should be part of js-waku code, as tracked in https://github.com/waku-org/js-waku/issues/1326. Or are you doing this to dogfood a logic?

2024-02-19 07:16 UTC, danisharora099 commented
Closing -- merged in js-waku with https://github.com/waku-org/js-waku/pull/1811

2024-02-19 07:16 UTC, closed without merging